google_analytics:
#theme: jekyll-theme-cayman
remote_theme: pages-themes/cayman@v0.2.0
plugins:
    - jekyll-remote-theme
github: [metadata]

title: 'Internet transparency'
description: 'Internet transparency research project'
logo: "pics/UT_Logo_2400_Sta_Black_EN.png"

navigation_header:
- title: Home
  url: /
- title: Contact
  url: /contact/